#!/usr/bin/env bash
set -euo pipefail
shopt -s extglob

cat <<HEREDOC > /opt/julia
#!/usr/bin/env bash
DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' `which julia` "\$@"
HEREDOC

chmod +x /opt/julia

export PATH=/opt:"$PATH"

echo "PATH is now $PATH"
echo "The content of /opt/julia is"
cat /opt/julia
echo "which julia gives `which julia`"
echo "julia -e versioninfo()"
julia -e "using InteractiveUtils; versioninfo()"
